### ISSUE TITLE
Feed's Specifically for Users/Profiles don't paginate and exclude users

### ISSUE THREAD

**Issue by bawanyadam** [jcsalterego/Contrails#10]
Reference config: https://github.com/bawanyadam/Contrails-LoveIsland/blob/main/CONFIG.md

+Noticed 3-4 of the profiles not being loaded into the feed on Bsky at all. Not sure how it determines to pick who shows and who doesn't lol. The order of the profiles in CONFIG.md have no effect on that.

**Comment by jcsalterego** [comment]
The free tier for Cloudflare Workers has a limited set of outgoing network calls, which limits Contrails. There's a `safeMode` setting which is set to `true` by default. If you turn this off and Deploy to Cloudflare without a paid tier, the whole feed will error out.

So unfortunately, you will have to upgrade to the $5/mo tier in Cloudflare and set `safeMode` to `false`, or reduce the number of terms.

**Comment by bawanyadam** [comment]
Thanks Jerry. Going to mess around and do the upgraded tier and see how it goes.

As always, appreciate the help and feedback. 👑

**Comment by bawanyadam** [comment]
New config.md after upgarding to the $5 workers tier: https://github.com/bawanyadam/Contrails-RealOnes/blob/main/CONFIG.md
