### ISSUE TITLE
FEATURE: Denylist

### ISSUE THREAD

**Issue by StuBlad** [jcsalterego/Contrails#13]
Having the ability to have a denylist to exclude skeets by specific users would be excellent. If possible, the ability to reference a mute list may also be great so this list could be public.

**Comment by StuBlad** [comment]
Would it be possible to make it so you could exclude skeets by a specific user entirely, but also have the ability to still display that persons skeets, but not if their skeet includes a specific search term?

i.e. you want someone to stay on the feed, but occasionally they post content that's nsfw, so if they mention nsfw in their skeet, it won't show up, but the rest of their skeets will.

**Comment by jcsalterego** [comment]
@StuBlad Possibly. I'll have to think about the tradeoffs here on adding complexity for the filtering logic. At some point, it might make sense to write custom code for that.

**Comment by StuBlad** [comment]
Just want to add on to this issue a little more. It would be just as good, if not perhaps even better, to be able to just exclude certain terms from appearing in a feed.

So for my FFXIV feed for example, if the term FFXIV shows up then display it in feed, but if a post contains both FFXIV AND nsfw, then exclude it. I think Contrails already supports that for including posts in the feed, would it be difficult to just take that logic and then just make it exclude posts instead?

That might be an easier win and more powerful initially than excluding a single user and having to filter out specific posts of theirs.

**Comment by bawanyadam** [comment]
@StuBlad Check out my modified feedgen.js here: https://github.com/bawanyadam/jeopardy-sky/blob/675c7083a533183abfe68f15bac23975e7bebd2b/cloudflare-worker/bsky-feedgen.js#L122

I've made a few feeds now and have continued to use this regex exact match function, and here you can see it explicitly will not including posts that contain "nsfw." This can also be adjusted to be "#nsfw" etc. From there you just have to implement the exact match logic into the feed build right below.

**Comment by StuBlad** [comment]
> Thanks for the bump. I've been a bit swamped lately but this is the top of the list for the next Contrails update.

Hi Jerry, just bumping this again to see if you are still developing Contrails. I love it so much and recommend it to everyone 😃

**Comment by jcsalterego** [comment]
@StuBlad Oh no it's already October! I haven't cracked open Contrails in a while but I'll think on this a little bit this week.

**Comment by jcsalterego** [comment]
@StuBlad All set, check it out - let me know if you have any questions.
