### ISSUE TITLE
"Publish Feed Generators" step failing: "Process completed with exit code 1."

### ISSUE THREAD

**Issue by ReadyEdgemont** [jcsalterego/Contrails#14]
tl;dr - getting error "Process completed with exit code 1.", is there a solution to that? Code below

`Run cd feed-generator/

added [14](https://github.com/ReadyEdgemont/Bluesky-Contrails-Hockey/actions/runs/5651260388/job/15309072600#step:6:15)7 packages, and audited 148 packages in 10s

13 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
FEEDGEN_HOSTNAME=bluesky-worker-hockey.rockerdude80.workers.dev
yarn run v1.22.19
$ ts-node publishFeedGenerators.ts
/home/runner/work/Bluesky-Contrails-Hockey/Bluesky-Contrails-Hockey/feed-generator/node_modules/@atproto/xrpc/src/client.ts:125
        throw new XRPCError(resCode, res.body.error, res.body.message)
              ^
XRPCError: Invalid identifier or password
    at ServiceClient.call (/home/runner/work/Bluesky-Contrails-Hockey/Bluesky-Contrails-Hockey/feed-generator/node_modules/@atproto/xrpc/src/client.ts:125:[15](https://github.com/ReadyEdgemont/Bluesky-Contrails-Hockey/actions/runs/5651260388/job/15309072600#step:6:16))
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async _AtpAgent.login (/home/runner/work/Bluesky-Contrails-Hockey/Bluesky-Contrails-Hockey/feed-generator/node_modules/@atproto/api/src/agent.ts:120:[19](https://github.com/ReadyEdgemont/Bluesky-Contrails-Hockey/actions/runs/5651260388/job/15309072600#step:6:20))
    at async publishAll (/home/runner/work/Bluesky-Contrails-Hockey/Bluesky-Contrails-Hockey/feed-generator/publishFeedGenerators.ts:13:3) {
  status: 401,
  error: 'AuthenticationRequired',
  success: false
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.`

First off, Jerry, thank you for putting your time and effort into Contrails, really hoping the issue I'm running into though is a quick solve.

I came across Contrails thanks to @lazylazyjane.bksy.social, and I was looking to set up a hockey thread agnostic of teams and just start adding all the hockey related folks I could to it for my own viewing. Again, thanks for setting this up, hope to hear from you soon!

**Comment by jcsalterego** [comment]
@ReadyEdgemont Try resetting your BLUESKY_HANDLE and BLUESKY_APP_PASSWORD in the variables and secrets. It's saying that the login doesn't work. One gotcha that some people have run into is the handle doesn't need a `@`.

Jane rocks.

**Comment by ReadyEdgemont** [comment]
Wow, it's always the little things like that which get you. That worked! Might I recommend in the main project to use examples for each variable / secret like you did with the CONFIG.md sections so someone like me doesn't trip again?

Thanks for all of your help and the speedy response!

**Comment by jcsalterego** [comment]
Yep, that's a fine suggestion and I need to go back and do a lot of documentation and cleanup. Thanks!

**Comment by bawanyadam** [comment]
When I had my first take at Contrails the “ BLUESKY_HANDLE” variable mention in the Readme.md mentions using the full profile url which kept throwing me the same error until I changed it to ‘name.bsky.social’ only. Might be worth updating that to prevent confusion.

Love u king

**Comment by jcsalterego** [comment]
@bawanyadam Thank you sir, duly noted
