### ISSUE TITLE
Receiving an error after upgrading and trying to publish feed updates

### ISSUE THREAD

**Issue by tigwyk** [jcsalterego/Contrails#19]
Hi @jcsalterego, recently I upgraded from an older version of Contrails and it seems to have happily layered your changes over my minor config file changes, no complaints from Git about any conflicts, so that seemed fine.

Now that I've made some changes to my feeds (their search terms, specifically) I'm trying to publish a new version and I'm receiving an error back after running the Publish Feed Generators github workflow:
> Error: The bluesky server is not ready to accept published custom feeds yet
    at publishAll (/home/runner/work/Contrails/Contrails/feed-generator/publishFeedGenerators.ts:18:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

It doesn't seem to matter what I change, I always receive this error. I updated my Bluesky app password and handle, just in case, but it doesn't complain about those. I'm trying to figure out where the error's generated during the process and what I should be checking.

**Comment by tigwyk** [comment]
Interestingly enough, somewhere in the process my feeds are being updated because I recognize that their results now match the search terms I updated even though I'm getting an error in the publish workflow.

**Comment by jcsalterego** [comment]
@tigwyk I saw reports of this last week but haven't been able to investigate. Will update when I can, and thanks for opening an issue

**Comment by jcsalterego** [comment]
Finally fixed this. If you don't want to upgrade, you can simply choose to yeet the following lines

https://github.com/jcsalterego/Contrails/commit/9e6a8085c1f680f880793ffe8ccbea3cb0cabd45
