### ISSUE TITLE
Error unterminated string

### ISSUE THREAD

**Issue by samuk** [jcsalterego/Contrails#24]
![unterminated-string](https://github.com/jcsalterego/Contrails/assets/400875/f64e7a56-d846-4a4c-920e-fbd9ca30db86)

When I try to deploy I get:

 ⛅️ wrangler 3.20.0
-------------------

✘ [ERROR] Unterminated string

    /github/workspace/wrangler.toml:1:31:
      1 │ name = "worker-small-night-fd13

Any idea why?

**Comment by jcsalterego** [comment]
Are you missing an ending quote in your file?

**Comment by samuk** [comment]
![variable](https://github.com/jcsalterego/Contrails/assets/400875/bb7807fb-280e-4475-b903-8260d827e343)

This is how the variable looks in the Github WebUI. 

Should I be adding "quotes" to that?

**Comment by jcsalterego** [comment]
Ah, I think the problem is there's a newline/enter in that variable. Can you try removing that from the CLOUDFLARE_WORKER_NAME Value field?

So if you select all in that field, you should see: `worker-small-night-fd13` instead of

```
worker-small-night-fd13

```

**Comment by samuk** [comment]
Thanks that has indeed resolved that. Apologies I thought I had tried deleting any extra spaces/breaks, but clearly not.

I do now run into this issue, but I'll investigate that unless you have any insights into what I've done wrong?
![missingURL](https://github.com/jcsalterego/Contrails/assets/400875/66c9e847-f668-40d7-8be8-4b9b181cb051)

**Comment by jcsalterego** [comment]
@samuk Based on your action https://github.com/samuk/bsky_robot_list/actions/runs/7209257611/job/19639831726 it looks like there's another newline in your account ID perhaps? I'd run through your variables and make sure none of them have the same newline issue.
